### PR TITLE
Document safety analysis approach

### PR DESCRIPTION
**Pull request by reiterative**
Describing OSEP's proposed approach to safety analysis for Linux, for sharing with the wider ELISA (and open source ) community.

### CODE REVIEW

**Comment by igor-stoppa** [comment]
I am not proposing changes because I am not sure what woule be the best way to phrase hte thoughts below, but here comes nothing:

- I would want to have further point that details how linux - as it is now - might already support some f those goals
- similarly, I would want to have also a list of what impediments linux might introduce in meeting those goals; in this regard, I think it's important to differentiate between gaps and real impediments, where the linux design actively goes against safety goals, because gaps can be filled, but if something is designed in a certain way, which happens to hamper safety, then it is necessary to introduce mitigations that do not jeopardize the *other* non safety goals that such component was supporting. Someone might decide to de-prioritize them, as trade-off for improved safety, but then it should be clear what is being given up.

**Comment by reiterative** [comment]
Thanks for your inputs @igor-stoppa.

Please check the updated text and confirm that we have addressed your points, and [review / approve](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews) if you are happy.

**Comment by reiterative** [comment]
Updated to move the approach text into its own directory, where we can begin to document both the steps for applying the approach and our results.

**Review by kent-ul — APPROVED** [review]
Review complete; no comments.

**Pull request merged**
